//_\TLV_version 1d: tl-x.org, generated by SandPiper(TM) 1.14-2022/10/10-beta-Pro
//_\source wip.tlv 79

//_\SV
`default_nettype none
module serv_rf_if
  #(parameter WITH_CSR = 1,
    parameter W = 1,
    parameter B = W-1
  )
  (//RF Interface
   input wire                 i_cnt_en,
   output wire [4+WITH_CSR:0] o_wreg0,
   output wire [4+WITH_CSR:0] o_wreg1,
   output wire                o_wen0,
   output wire                o_wen1,
   output wire [B:0]  o_wdata0,
   output wire [B:0]  o_wdata1,
   output wire [4+WITH_CSR:0] o_rreg0,
   output wire [4+WITH_CSR:0] o_rreg1,
   input wire  [B:0] i_rdata0,
   input wire  [B:0] i_rdata1,

   //Trap interface
   input wire                 i_trap,
   input wire                 i_mret,
   input wire [B:0] i_mepc,
   input wire                      i_mtval_pc,
   input wire [B:0] i_bufreg_q,
   input wire [B:0] i_bad_pc,
   output wire [B:0] o_csr_pc,
   //CSR interface
   input wire                 i_csr_en,
   input wire [1:0]           i_csr_addr,
   input wire [B:0] i_csr,
   output wire [B:0] o_csr,
   //RD write port
   input wire                 i_rd_wen,
   input wire [4:0]           i_rd_waddr,
   input wire [B:0] i_ctrl_rd,
   input wire [B:0] i_alu_rd,
   input wire                 i_rd_alu_en,
   input wire [B:0] i_csr_rd,
   input wire                 i_rd_csr_en,
   input wire [B:0] i_mem_rd,
   input wire                 i_rd_mem_en,

   //RS1 read port
   input wire [4:0]           i_rs1_raddr,
   output wire [B:0] o_rs1,
   //RS2 read port
   input wire [4:0]           i_rs2_raddr,
   output wire [B:0] o_rs2);
// ---------- Generated Code Inlined Here (before 1st \TLV) ----------
// Generated by SandPiper(TM) 1.14-2022/10/10-beta-Pro from Redwood EDA, LLC.
// Redwood EDA, LLC does not claim intellectual property rights to this file and provides no warranty regarding its correctness or quality.


// For silencing unused signal messages.
`define BOGUS_USE(ignore)





//
// Signals declared top-level.
//

// For |default$alu_rd.
logic [B : 0] DEFAULT_alu_rd_a0;

// For |default$bad_pc.
logic [B : 0] DEFAULT_bad_pc_a0;

// For |default$bufreg_q.
logic [B : 0] DEFAULT_bufreg_q_a0;

// For |default$cnt_en.
logic DEFAULT_cnt_en_a0;

// For |default$csr.
logic [B : 0] DEFAULT_csr_a0;

// For |default$csr_addr.
logic [1 : 0] DEFAULT_csr_addr_a0;

// For |default$csr_en.
logic DEFAULT_csr_en_a0;

// For |default$csr_in.
logic [B : 0] DEFAULT_csr_in_a0;

// For |default$csr_pc.
logic [B : 0] DEFAULT_csr_pc_a0;

// For |default$csr_rd.
logic [B : 0] DEFAULT_csr_rd_a0;

// For |default$ctrl_rd.
logic [B : 0] DEFAULT_ctrl_rd_a0;

// For |default$mem_rd.
logic [B : 0] DEFAULT_mem_rd_a0;

// For |default$mepc.
logic [B : 0] DEFAULT_mepc_a0;

// For |default$mret.
logic DEFAULT_mret_a0;

// For |default$mtval.
logic [B : 0] DEFAULT_mtval_a0;

// For |default$mtval_pc.
logic DEFAULT_mtval_pc_a0;

// For |default$rd.
logic [B : 0] DEFAULT_rd_a0;

// For |default$rd_alu_en.
logic DEFAULT_rd_alu_en_a0;

// For |default$rd_csr_en.
logic DEFAULT_rd_csr_en_a0;

// For |default$rd_mem_en.
logic DEFAULT_rd_mem_en_a0;

// For |default$rd_waddr.
logic [4 : 0] DEFAULT_rd_waddr_a0;

// For |default$rd_wen.
logic DEFAULT_rd_wen_a0;

// For |default$rd_wen_in.
logic DEFAULT_rd_wen_in_a0;

// For |default$rdata0.
logic [B : 0] DEFAULT_rdata0_a0;

// For |default$rdata1.
logic [B : 0] DEFAULT_rdata1_a0;

// For |default$rreg0.
logic [4 + WITH_CSR : 0] DEFAULT_rreg0_a0;

// For |default$rreg1.
logic [4 + WITH_CSR : 0] DEFAULT_rreg1_a0;

// For |default$rs1.
logic [B : 0] DEFAULT_rs1_a0;

// For |default$rs1_raddr.
logic [4 : 0] DEFAULT_rs1_raddr_a0;

// For |default$rs2.
logic [B : 0] DEFAULT_rs2_a0;

// For |default$rs2_raddr.
logic [4 : 0] DEFAULT_rs2_raddr_a0;

// For |default$sel_rs2.
logic DEFAULT_sel_rs2_a0;

// For |default$trap.
logic DEFAULT_trap_a0;

// For |default$wdata0.
logic [B : 0] DEFAULT_wdata0_a0;

// For |default$wdata1.
logic [B : 0] DEFAULT_wdata1_a0;

// For |default$wen0.
logic DEFAULT_wen0_a0;

// For |default$wen1.
logic DEFAULT_wen1_a0;

// For |default$wreg0.
logic [4 + WITH_CSR : 0] DEFAULT_wreg0_a0;

// For |default$wreg1.
logic [4 + WITH_CSR : 0] DEFAULT_wreg1_a0;


// ---------- Generated Code Ends ----------
//_\TLV
   // Connect Verilog inputs:
   //_|default
      //_@0
         assign DEFAULT_cnt_en_a0 = i_cnt_en;
         assign DEFAULT_rd_wen_in_a0 = i_rd_wen;
         assign DEFAULT_rd_waddr_a0[4 : 0] = i_rd_waddr;
         assign DEFAULT_ctrl_rd_a0[B : 0] = i_ctrl_rd;
         assign DEFAULT_alu_rd_a0[B : 0] = i_alu_rd;
         assign DEFAULT_rd_alu_en_a0 = i_rd_alu_en;
         assign DEFAULT_csr_rd_a0[B : 0] = i_csr_rd;
         assign DEFAULT_rd_csr_en_a0 = i_rd_csr_en;
         assign DEFAULT_mem_rd_a0[B : 0] = i_mem_rd;
         assign DEFAULT_rd_mem_en_a0 = i_rd_mem_en;
         assign DEFAULT_rs1_raddr_a0[4 : 0] = i_rs1_raddr;
         assign DEFAULT_rs2_raddr_a0[4 : 0] = i_rs2_raddr;
         assign DEFAULT_rdata0_a0[B : 0] = i_rdata0;
         assign DEFAULT_rdata1_a0[B : 0] = i_rdata1;
         assign DEFAULT_trap_a0 = i_trap;
         assign DEFAULT_mret_a0 = i_mret;
         assign DEFAULT_mepc_a0[B : 0] = i_mepc;
         assign DEFAULT_mtval_pc_a0 = i_mtval_pc;
         assign DEFAULT_bufreg_q_a0[B : 0] = i_bufreg_q;
         assign DEFAULT_bad_pc_a0[B : 0] = i_bad_pc;
         assign DEFAULT_csr_en_a0 = i_csr_en;
         assign DEFAULT_csr_addr_a0[1 : 0] = i_csr_addr;
         assign DEFAULT_csr_in_a0[B : 0] = i_csr;
   //_\source wip.tlv 8   // Instantiated from wip.tlv, 158 as: m5+serv_rf_if(/top)
      //_|default
         //_@0
            /*
             ********** Write side ***********
             */
            assign DEFAULT_rd_wen_a0 = DEFAULT_rd_wen_in_a0 & ( | DEFAULT_rd_waddr_a0);
            assign DEFAULT_rd_a0[B : 0] =
                {W{DEFAULT_rd_alu_en_a0}} & DEFAULT_alu_rd_a0 |
                ( | WITH_CSR ? {W{DEFAULT_rd_csr_en_a0}} & DEFAULT_csr_rd_a0 : {W{1'b0}}) |  // relevant if (|WITH_CSR)
                {W{DEFAULT_rd_mem_en_a0}} & DEFAULT_mem_rd_a0 |
                DEFAULT_ctrl_rd_a0;
            assign DEFAULT_mtval_a0[B : 0] = DEFAULT_mtval_pc_a0 ? DEFAULT_bad_pc_a0 : DEFAULT_bufreg_q_a0;  // relevant if (|WITH_CSR)
            assign DEFAULT_wdata0_a0[B : 0] = ( | WITH_CSR) & DEFAULT_trap_a0 ? DEFAULT_mtval_a0 : DEFAULT_rd_a0;
            assign DEFAULT_wdata1_a0[B : 0] = ( | WITH_CSR) ? (DEFAULT_trap_a0 ? DEFAULT_mepc_a0 : DEFAULT_csr_in_a0) : {W{1'b0}};
   
            /* Port 0 handles writes to mtval during traps and rd otherwise
             * Port 1 handles writes to mepc during traps and csr accesses otherwise
             *
             * GPR registers are mapped to address 0-31 (bits 0xxxxx).
             * Following that are four CSR registers
             * mscratch 100000
             * mtvec    100001
             * mepc     100010
             * mtval    100011
             */
   
            assign DEFAULT_wreg0_a0[4 + WITH_CSR : 0] = ( | WITH_CSR) & DEFAULT_trap_a0 ? {6'b100011} : {1'b0, DEFAULT_rd_waddr_a0};
            assign DEFAULT_wreg1_a0[4 + WITH_CSR : 0] = ( | WITH_CSR) ? (DEFAULT_trap_a0 ? {6'b100010} : {4'b1000, DEFAULT_csr_addr_a0}) : 5'd0;
   
            assign DEFAULT_wen0_a0 = DEFAULT_cnt_en_a0 & (( | WITH_CSR) & DEFAULT_trap_a0 | DEFAULT_rd_wen_a0);
            assign DEFAULT_wen1_a0 = ( | WITH_CSR) ? (DEFAULT_cnt_en_a0 & (DEFAULT_trap_a0 | DEFAULT_csr_en_a0)) : 1'b0;
   
            /*
             ********** Read side ***********
             */
   
            //0 : RS1
            //1 : RS2 / CSR
   
            assign DEFAULT_rreg0_a0[4 + WITH_CSR : 0] = {1'b0, DEFAULT_rs1_raddr_a0};
   
            /*
             The address of the second read port (o_rreg1) can get assigned from four
             different sources
   
             Normal operations : i_rs2_raddr
             CSR access        : i_csr_addr
             trap              : MTVEC
             mret              : MEPC
   
             Address 0-31 in the RF are assigned to the GPRs. After that follows the four
             CSRs on addresses 32-35
   
             32 MSCRATCH
             33 MTVEC
             34 MEPC
             35 MTVAL
   
             The expression below is an optimized version of this logic
             */
            assign DEFAULT_sel_rs2_a0 = ! (DEFAULT_trap_a0 | DEFAULT_mret_a0 | DEFAULT_csr_en_a0);  // relevant if (|WITH_CSR)
            assign DEFAULT_rreg1_a0[4 + WITH_CSR : 0] = ( | WITH_CSR) ?
                {~ DEFAULT_sel_rs2_a0,
                 DEFAULT_rs2_raddr_a0[4 : 2] & {3{DEFAULT_sel_rs2_a0}},
                 {1'b0, DEFAULT_trap_a0} | {DEFAULT_mret_a0, 1'b0} | ({2{DEFAULT_csr_en_a0}} & DEFAULT_csr_addr_a0) | ({2{DEFAULT_sel_rs2_a0}} & DEFAULT_rs2_raddr_a0[1 : 0])} :
                DEFAULT_rs2_raddr_a0;
   
            assign DEFAULT_rs1_a0[B : 0] = DEFAULT_rdata0_a0;
            assign DEFAULT_rs2_a0[B : 0] = DEFAULT_rdata1_a0;
            assign DEFAULT_csr_a0[B : 0] = ( | WITH_CSR) ? (DEFAULT_rdata1_a0 & {W{DEFAULT_csr_en_a0}}) : {W{1'b0}};
            assign DEFAULT_csr_pc_a0[B : 0] = ( | WITH_CSR) ? DEFAULT_rdata1_a0 : {W{1'b0}};
   //_\end_source
   // Connect Verilog outputs:
   //_|default
      //_@0
         assign o_wdata0 = DEFAULT_wdata0_a0;
         assign o_wdata1 = DEFAULT_wdata1_a0;
         assign o_wreg0 = DEFAULT_wreg0_a0;
         assign o_wreg1 = DEFAULT_wreg1_a0;
         assign o_wen0 = DEFAULT_wen0_a0;
         assign o_wen1 = DEFAULT_wen1_a0;
         assign o_rreg0 = DEFAULT_rreg0_a0;
         assign o_rreg1 = DEFAULT_rreg1_a0;
         assign o_rs1 = DEFAULT_rs1_a0;
         assign o_rs2 = DEFAULT_rs2_a0;
         assign o_csr = DEFAULT_csr_a0;
         assign o_csr_pc = DEFAULT_csr_pc_a0;
//_\SV
endmodule


// Undefine macros defined by SandPiper.
`undef BOGUS_USE
